# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qWFW2cGmRJEGR-hYx06kh6UryPP17yOi
"""

import numpy as np
import pandas as pd

# 1. Generate synthetic dataset
n_obs = 600
t = np.arange(n_obs)
season1 = np.sin(t * 2 * np.pi / 50)
season2 = np.cos(t * 2 * np.pi / 80)
trend = 0.01 * t
noise = np.random.normal(0, 0.2, n_obs)
df = pd.DataFrame({
    'ds': pd.date_range(start='2022-01-01', periods=n_obs, freq='D'),
    'y': 3*season1 + 2*season2 + trend + noise
})

# 2. Prophet model (basic)
from prophet import Prophet
m = Prophet()
m.fit(df)
future = m.make_future_dataframe(periods=60)
forecast = m.predict(future)

from sklearn.metrics import mean_squared_error, mean_absolute_error
# Prophet performance on holdout
pred_prophet = forecast['yhat'][-60:].values
true = df['y'][-60:].values
prophet_rmse = np.sqrt(mean_squared_error(true, pred_prophet))
prophet_mae = mean_absolute_error(true, pred_prophet)

print("Prophet RMSE:", prophet_rmse, "MAE:", prophet_mae)

# 3. LSTM model (basic)
from sklearn.preprocessing import MinMaxScaler
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

window = 20
vals = df['y'].values.reshape(-1, 1)
scaler = MinMaxScaler()
vals_scaled = scaler.fit_transform(vals)
X, y_lstm = [], []
for i in range(window, len(vals_scaled)):
    X.append(vals_scaled[i-window:i])
    y_lstm.append(vals_scaled[i])
X = np.array(X)
y_lstm = np.array(y_lstm)
split = int(0.8 * len(X))
X_train, X_test = X[:split], X[split:]
y_train, y_test = y_lstm[:split], y_lstm[split:]

model = Sequential([
    LSTM(64, input_shape=(X_train.shape[1], X_train.shape[2]), return_sequences=True),
    Dropout(0.2),
    LSTM(32),
    Dropout(0.2),
    Dense(16, activation='relu'),
    Dense(1)
])
model.compile(optimizer='adam', loss='mse', metrics=['mae'])
model.fit(X_train, y_train, epochs=28, batch_size=32, validation_data=(X_test, y_test), verbose=0)

pred_lstm = model.predict(X_test)
lstm_rmse = np.sqrt(mean_squared_error(y_test, pred_lstm))
lstm_mae = mean_absolute_error(y_test, pred_lstm)
print("LSTM RMSE:", lstm_rmse, "MAE:", lstm_mae)